class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror3'
        self.UnzipMirrorCommand = 'unzipmirror3'
        self.TarMirrorCommand = 'tarmirror3'
        self.CancelMirror = 'cancel3'
        self.CancelAllCommand = 'cancelall3'
        self.ListCommand = 'list3'
        self.StatusCommand = 'status3'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize3'
        self.UnAuthorizeCommand = 'unauthorize3'
        self.AddSudoCommand = 'addsudo3'
        self.RmSudoCommand = 'rmsudo3'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help3'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone3'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch3'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.MediaInfoCommand = 'mediainfo'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'

BotCommands = _BotCommands()
